In [1]:
import cv2
import numpy as np

img = cv2.imread("../data/lena.png")

In [13]:
img_rect = img.copy()
cv2.rectangle(img_rect, (60,40), (420, 510), (0,0,255), 3)

while True:
    cv2.imshow('image', img_rect)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [17]:
img_line = img.copy()
cv2.line(img_line, (60,40), (420, 510), (0,0,255), 10)

while True:
    cv2.imshow('image', img_line)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [23]:
img_text = img.copy()
cv2.putText(img_text,'Lena', (60,40), 5, 3, (0,0,255), 3)

while True:
    cv2.imshow('image', img_text)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [38]:
img_hw1 = img.copy()
point1 = (60,40)
point2 = (420,510)

img_hw1 = cv2.cvtColor(img_hw1, cv2.COLOR_BGR2HSV)

In [39]:
img_hw1[:,:,-1] == img_hw1[..., -1]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [41]:
img_hw1[..., -1] = cv2.equalizeHist(img_hw1[..., -1])
img_hw1 = cv2.cvtColor(img_hw1, cv2.COLOR_HSV2BGR)

cv2.rectangle(img_hw1, point1, point2, (0,0,255), 3)

img_hw1 = img_hw1[:, ::-1, :]

img_hw1 = cv2.resize(img_hw1, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_LINEAR)

while True:
    cv2.imshow('image', img_hw1)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [81]:
img_hw2 = img.copy()

Point1 = [60, 40]
Point2 = [420, 510]

img_hw2 = cv2.cvtColor(img_hw2, cv2.COLOR_BGR2HSV)

img_hw2[..., -1] = cv2.equalizeHist(img_hw2[..., -1])

img_hw2 = cv2.cvtColor(img_hw2, cv2.COLOR_HSV2BGR)

h, w = img_hw2.shape[:2]

img_hw2 = img_hw2[:, ::-1, :]

Point1[0] = w - Point1[0]
Point2[0] = w - Point2[0]



In [82]:
fx = 0.5
fy = 0.5
resize_col = int(img_hw2.shape[1]*fx)
resize_row = int(img_hw2.shape[0]*fy)

In [83]:
resize_col

256

In [84]:
M_scale = np.array([[fx, 0, 0],[0, fy, 0]])
img_hw2 = cv2.warpAffine(img_hw2, M_scale, (resize_row, resize_col))

while True:
    cv2.imshow('image', img_hw2)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [85]:
bbox = np.array((Point1, Point2), dtype=np.float32)

In [86]:
bbox

array([[452.,  40.],
       [ 92., 510.]], dtype=float32)

In [87]:
homo_coor_result = np.dot(M_scale.T, bbox)
homo_coor_result = homo_coor_result.astype('uint8')

In [88]:
homo_coor_result

array([[226,  20],
       [ 46, 255],
       [  0,   0]], dtype=uint8)

In [89]:
scale_point1 = tuple(homo_coor_result[0])
scale_point2 = tuple(homo_coor_result[1])
print('origin point1={}, origin point2={}'.format(Point1, Point2))
print('resize point1={}, resize point2={}'.format(scale_point1, scale_point2))

origin point1=[452, 40], origin point2=[92, 510]
resize point1=(226, 20), resize point2=(46, 255)


In [90]:
cv2.rectangle(img_hw2, scale_point1, scale_point2, (0, 0, 255), 3)

while True:
    cv2.imshow('image', img_hw2)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break