In [1]:
import cv2
import numpy as np

img = cv2.imread("../data/lena.png")

In [2]:
img_blur = img.copy()

# 重複多次 Gaussian 模糊的操作來加深模糊的程度
for i in range(100):
    img_blur = cv2.GaussianBlur(img_blur, (5,5), 0)

img_show = np.hstack((img, img_blur))
while True:
    cv2.imshow('Gaussian Blur', img_show)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [3]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

img_sobel_x = cv2.Sobel(img_gray, cv2.CV_16S, dx = 1, dy = 0, ksize = 3)

In [4]:
#have negative value
img_sobel_x 

array([[   0,    0,   -4, ...,  -64, -168,    0],
       [   0,    0,   -4, ...,  -64, -168,    0],
       [   0,    0,   -4, ...,  -64, -168,    0],
       ...,
       [   0,   29,   19, ...,    3,  -14,    0],
       [   0,   40,   25, ...,   15,    6,    0],
       [   0,   44,   28, ...,   20,   16,    0]], dtype=int16)

In [5]:
img_sobel_x = cv2.convertScaleAbs(img_sobel_x)
img_sobel_x

array([[  0,   0,   4, ...,  64, 168,   0],
       [  0,   0,   4, ...,  64, 168,   0],
       [  0,   0,   4, ...,  64, 168,   0],
       ...,
       [  0,  29,  19, ...,   3,  14,   0],
       [  0,  40,  25, ...,  15,   6,   0],
       [  0,  44,  28, ...,  20,  16,   0]], dtype=uint8)

In [6]:
img_sobel_y = cv2.Sobel(img_gray, cv2.CV_16S, dx=0, dy=1, ksize=3)
img_sobel_y = cv2.convertScaleAbs(img_sobel_y)
img_sobel_y.dtype

dtype('uint8')

In [7]:
#we cannot square uint8 directly because it'll cause overflow problem, so I convert to unint16 first
img_sobel_xy = np.sqrt(np.square(img_sobel_x.astype('uint16')) + np.square(img_sobel_y).astype('uint16'))
img_sobel_xy = img_sobel_xy.astype('uint8')

img_show = np.hstack((img_sobel_x, img_sobel_y, img_sobel_xy))
while True:
    cv2.imshow('Edge Detection', img_show)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [21]:
np.square(img_sobel_x)

array([[  0,   0,  16, ...,   0,  64,   0],
       [  0,   0,  16, ...,   0,  64,   0],
       [  0,   0,  16, ...,   0,  64,   0],
       ...,
       [  0,  73, 105, ...,   9, 196,   0],
       [  0,  64, 113, ..., 225,  36,   0],
       [  0, 144,  16, ..., 144,   0,   0]], dtype=uint8)

### Homework Start

In [10]:
img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_sobelx = cv2.Sobel(img_grey, cv2.CV_16S, dx=1, dy=0, ksize=3)
img_sobelx = cv2.convertScaleAbs(img_sobelx)

img_sobelx_uint8 = cv2.Sobel(img_grey, cv2.CV_8U, dx=1, dy=0, ksize=3)

img_show = np.hstack((img_grey, img_sobelx, img_sobelx_uint8))
while True:
    # 比較 Sobel 邊緣檢測的過程中針對負數操作的不同產生的差異
    cv2.imshow('Edge Detection', img_show)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [11]:
# 求二次導數取得邊緣檢測結果
img_sobelxx = cv2.Sobel(img_grey, cv2.CV_16S, dx=2, dy=0, ksize=3)
img_sobelxx = cv2.convertScaleAbs(img_sobelxx)

img_show = np.hstack((img_grey, img_sobelx, img_sobelxx))
while True:
    cv2.imshow('Edge Detection', img_show)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

[SOBEL AND LAPLACIAN](https://www.bogotobogo.com/python/OpenCV_Python/python_opencv3_Image_Gradient_Sobel_Laplacian_Derivatives_Edge_Detection.php)